version: '3'

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: always
    ports:
      - "8000:80" 
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
    depends_on:
      - db
    networks:
      - my_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - my_network

  db:
    build: ./requirements/mariadb
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER:     ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - my_network

volumes:
  wordpress_data:
  db_data:

networks:
  my_network:
